### ISSUE TITLE
[feat] 버튼 2개 공통 모달 제작

### ISSUE THREAD

**Issue by uiop5809** [Kusitms-28th-Meetup-D/frontend#29]
### 목적
공통 모달 제작

### 작업 상세 내용
- [ ] 공통 모달

### 유의사항
재사용 가능하도록 만들어보겠습니다

**Comment by j2noo** [comment]
내가 만들게~` feat/29`

**Comment by uiop5809** [comment]
> 내가 만들게~` feat/29`

넹 너무 좋아요~
